### ISSUE TITLE
INTeger frequency value

### ISSUE THREAD

**Issue by juggie01** [JChristensen/gpsFreq#1]
I'd like to use the sketch to get an integer value rather than a serial stream but am struggling to find it in the code

**Comment by JChristensen** [comment]
gpsFreq.freq (see [here](https://github.com/JChristensen/gpsFreq/blob/779487c929bab797c829428f3476ed27b65c9938/gpsFreq.h#L37))

**Comment by juggie01** [comment]
Thank you, very much appreciated - not sure how I missed that ... !!
